networks:
  blockchain-proxy:
    driver: bridge
services:
  blockchain-proxy-nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - blockchain-proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/0-blockchain-proxy.conf:/etc/nginx/conf.d/0-blockchain-proxy.conf
      - ./ssl:/etc/nginx/ssl/
