apiVersion: v1
kind: Service
metadata:
  name: {{ include "cronos-pos-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cronos-pos-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cronos-pos-node.labels" . | nindent 4 }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key | lower }}
      port: {{ $value }}
      targetPort: {{ $value }}
      protocol: TCP
    {{- end }}
